### ISSUE TITLE
Credo hook crashes when code does not compile correctly

### ISSUE THREAD

**Issue by roehst** [sds/overcommit#450]
If any file does not compile correctly with mix, the output from credo will include the following message, which contains lines not matching the expected file name / number / message pattern.

This leads to a crash.

Perhaps overcommit should warn the user when compiling fails.

This can get specially nasty when you fix your files and forget to add them with git add.

```

"Some source files could not be parsed correctly and are excluded:"
""
"   1) web/repos/api/x_x_repo.ex"
""
"web/repos/api/y_y_repo.ex:17:1: R: There should be no trailing white-space at the end of a line."
"web/repos/api/y_y_repo.ex:29:1: R: There should be no trailing white-space at the end of a line."
"web/repos/api/y_y_repo.ex:41:48: R: There should be no trailing white-space at the end of a line."
Analyze with credo............................................[Credo] FAILED
Hook raised unexpected error
can't convert nil into Integer
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/credo.rb:24:in `Integer'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/credo.rb:24:in `message'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/credo.rb:17:in `block in run'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/credo.rb:17:in `map'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/pre_commit/credo.rb:17:in `run'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/base.rb:45:in `block in run_and_transform'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/utils.rb:260:in `with_environment'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook/base.rb:45:in `run_and_transform'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook_runner.rb:152:in `run_hook'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook_runner.rb:88:in `block in consume'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook_runner.rb:85:in `loop'
/home/rodrigo/.rvm/gems/ruby-2.3.1/gems/overcommit-0.37.0/lib/overcommit/hook_runner.rb:85:in `consume'

```

**Comment by sds** [comment]
Thanks for reporting this issue, @roehst. Happy to accept a pull request with a fix. Thanks!

**Comment by hasitha** [comment]
I think this happens when an error spans more than one line. It looks like the pre commit hook splits up the output by new line, and then splits at `:` to get the line number. This is what's breaking when you have a new line inside the error message.

**Comment by sds** [comment]
Still happy to merge a pull request fixing this issue if it is still relevant. Closing due to age.
