### ISSUE TITLE
invalid byte sequence in UTF-8 on Win10

### ISSUE THREAD

**Issue by Antronin** [sds/overcommit#717]
Below is the git log when I enable overcommit's pre_commit hook:
```
invalid byte sequence in UTF-8
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/utils/file_utils.rb:67:in `win32_symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/utils/file_utils.rb:27:in `symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/utils.rb:271:in `broken_symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_context/pre_commit.rb:196:in `block in store_modified_times'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_context/pre_commit.rb:195:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_context/pre_commit.rb:195:in `store_modified_times'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_context/pre_commit.rb:48:in `setup_environment'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_runner.rb:42:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/interrupt_handler.rb:86:in `isolate_from_interrupts'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/hook_runner.rb:30:in `run'
.git/hooks/pre-commit:80:in `<main>'
Report this bug at https://github.com/sds/overcommit/issues
```
Because it is not mentioning any file name I'm not sure what exactly causes it. Please help.

**Comment by sds** [comment]
Thanks for the report, @Antronin.

This will be hard to debug without knowing what input results in this situation happening. Could you do us a favor and (temporarily) modify your `C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.53.0/lib/overcommit/utils/file_utils.rb` file so we can see the raw bytes?

```diff
diff --git a/lib/overcommit/utils/file_utils.rb b/lib/overcommit/utils/file_utils.rb
index cff2ce0b..7a3f4318 100644
--- a/lib/overcommit/utils/file_utils.rb
+++ b/lib/overcommit/utils/file_utils.rb
@@ -64,6 +64,7 @@ module Overcommit::Utils
       end

       def win32_symlink?(dir_output)
+        puts dir_output.bytes.inspect
         !(dir_output =~ /<SYMLINK>/).nil?
       end
     end
```

We are looking for output of the array of bytes. Thanks!

**Comment by sds** [comment]
Closing due to lack of response. Will welcome a pull request that fixes this issue!
