### ISSUE TITLE
Emoji in command output seems to break

### ISSUE THREAD

**Issue by clemens** [sds/overcommit#781]
The latest release seems to have an issue when emojis (or more general: UTF-8 characters) are used in a command's output.

Here's the error i'm getting:

```
Checks for vulnerable versions of 3rd party packages.......[NpmAudit] FAILED
Hook raised unexpected error
"\xF0" on US-ASCII
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/subprocess.rb:105:in `convert'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/subprocess.rb:105:in `to_utf8'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/subprocess.rb:55:in `spawn'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/utils.rb:187:in `execute'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_context/base.rb:33:in `execute_hook'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:85:in `run'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook/base.rb:47:in `block in run_and_transform'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/utils.rb:260:in `with_environment'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook/base.rb:47:in `run_and_transform'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_runner.rb:162:in `run_hook'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_runner.rb:98:in `block in consume'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_runner.rb:94:in `loop'
/var/lib/gems/2.5.0/gems/overcommit-0.59.0/lib/overcommit/hook_runner.rb:94:in `consume'
```

The command looks like this:

``` yaml
NpmAudit:
  description: 'Checks for vulnerable versions of 3rd party packages'
  enabled: true
  command: ['bin/npm-audit']
```

The binary looks like this:

``` bash
#!/bin/bash

$(npm bin)/better-npm-audit audit
```

The output from the command is this:

![Screenshot 2022-04-29 at 11 52 56](https://user-images.githubusercontent.com/3749/165922991-63460b03-d572-4106-84b1-ed62088d0cd4.png)

---

I'm assuming this is related to https://github.com/sds/overcommit/pull/766.

OS: Debian 10 in Docker container
overcommit version: 0.59.0 (it works fine in 0.58.0)

**Comment by clemens** [comment]
Here's how I've worked around it for now:

``` bash
#!/bin/bash

$(npm bin)/better-npm-audit audit > /dev/null && echo "All good!"
```

**Comment by Drowze** [comment]
I debugged this a bit but I'm still not sure about the proper fix... It also doesn't help that #766 didn't add a test documenting the intended behaviour of `to_utf8` method 🤔 

Here's a minimal Dockerfile to reproduce the bug:
```Dockerfile
FROM debian

RUN apt update -y && apt install -y ruby git && gem install bundler overcommit
WORKDIR some-dir

# setup a git repo with a utf-8 commit message
RUN git init && \
  git config --local user.name "Overcommit Tester" && \
  git config --local user.email "overcommit@example.com" && \
  git commit --allow-empty -m "🤝 UTF-8 text"

# add and install a pre-commit hook that checks a commit message
RUN echo "PreCommit:\n  CapitalizedSubject:\n    enabled: true" > .overcommit.yml && overcommit --install

# amend the commit to trigger the pre-commit hook; this raises an error
RUN git commit --amend --no-edit
```
