### ISSUE TITLE
FYI: unable to determine line number or type of error/warning for output: lockfile.rb

### ISSUE THREAD

**Issue by bmulholland** [sds/overcommit#846]
https://github.com/rubocop/rubocop/issues/12823 seems to cause an obscure error:

```
Unexpected output: unable to determine line number or type of error/warning for output:
/Users/bmulholland/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:66:in `rescue in parser'
/Users/bmulholland/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:60:in `parser'
```

Looks like they intend to fix that, but this error only happened on pre-commit hooks in overcommit, so posting here as an FYI.

**Comment by bmulholland** [comment]
As a workaround I made rubocop run using bundle exec with the config at https://github.com/sds/overcommit?tab=readme-ov-file#configuration

**Comment by bmulholland** [comment]
@ms-ati yes, see the workaround I posted
